variables:
  SOURCE_DIRECTORY:
    description: "Select the source directory"
    value: "home/ali" # Default value (can be modified)
    options:
      - "D://ali//" #--> windows format 
      - "/home/ali" #--> linux format

  GIT_REPO_URL:
    description: "Select the Git repository URL"
    value: "https://github.....git" # Default value (can be modified)
    options:
      - "https://github......git" # Enter dest repo


  COMMIT_MESSAGE:
    description: "The commit message for the Git push"
    value: "push done!"  # Default commit message

stages:
  - push

push:
  stage: push
  when: manual
  script:
    - python main.py
  tags:
    - pusher
